/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppointmentRouteImport } from './routes/appointment'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as CustomDesignRouteImport } from './routes/custom-design'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StudentWorkRouteImport } from './routes/student-work'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSectionRouteImport } from './routes/admin/$section'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminHomepageRouteImport } from './routes/admin/homepage'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopProductIdRouteImport } from './routes/shop.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentRoute = AppointmentRouteImport.update({
  id: '/appointment',
  path: '/appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomDesignRoute = CustomDesignRouteImport.update({
  id: '/custom-design',
  path: '/custom-design',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentWorkRoute = StudentWorkRouteImport.update({
  id: '/student-work',
  path: '/student-work',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSectionRoute = AdminSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminHomepageRoute = AdminHomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ShopProductIdRoute = ShopProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/custom-design': typeof CustomDesignRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRouteWithChildren
  '/student-work': typeof StudentWorkRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/custom-design': typeof CustomDesignRoute
  '/gallery': typeof GalleryRoute
  '/student-work': typeof StudentWorkRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/shop': typeof ShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/appointment': typeof AppointmentRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/custom-design': typeof CustomDesignRoute
  '/gallery': typeof GalleryRoute
  '/shop': typeof ShopRouteWithChildren
  '/student-work': typeof StudentWorkRoute
  '/admin/$section': typeof AdminSectionRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/homepage': typeof AdminHomepageRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/shop/$productId': typeof ShopProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/shop/': typeof ShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/courses'
    | '/custom-design'
    | '/gallery'
    | '/shop'
    | '/student-work'
    | '/admin/$section'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/products'
    | '/admin/testimonials'
    | '/shop/$productId'
    | '/admin/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/courses'
    | '/custom-design'
    | '/gallery'
    | '/student-work'
    | '/admin/$section'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/products'
    | '/admin/testimonials'
    | '/shop/$productId'
    | '/admin'
    | '/shop'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/appointment'
    | '/contact'
    | '/courses'
    | '/custom-design'
    | '/gallery'
    | '/shop'
    | '/student-work'
    | '/admin/$section'
    | '/admin/gallery'
    | '/admin/homepage'
    | '/admin/products'
    | '/admin/testimonials'
    | '/shop/$productId'
    | '/admin/'
    | '/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AppointmentRoute: typeof AppointmentRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  CustomDesignRoute: typeof CustomDesignRoute
  GalleryRoute: typeof GalleryRoute
  ShopRoute: typeof ShopRouteWithChildren
  StudentWorkRoute: typeof StudentWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointment': {
      id: '/appointment'
      path: '/appointment'
      fullPath: '/appointment'
      preLoaderRoute: typeof AppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-design': {
      id: '/custom-design'
      path: '/custom-design'
      fullPath: '/custom-design'
      preLoaderRoute: typeof CustomDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-work': {
      id: '/student-work'
      path: '/student-work'
      fullPath: '/student-work'
      preLoaderRoute: typeof StudentWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/$section': {
      id: '/admin/$section'
      path: '/$section'
      fullPath: '/admin/$section'
      preLoaderRoute: typeof AdminSectionRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/homepage': {
      id: '/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AdminHomepageRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/$productId': {
      id: '/shop/$productId'
      path: '/$productId'
      fullPath: '/shop/$productId'
      preLoaderRoute: typeof ShopProductIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminSectionRoute: typeof AdminSectionRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminHomepageRoute: typeof AdminHomepageRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminSectionRoute: AdminSectionRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminHomepageRoute: AdminHomepageRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ShopRouteChildren {
  ShopProductIdRoute: typeof ShopProductIdRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopProductIdRoute: ShopProductIdRoute,
  ShopIndexRoute: ShopIndexRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AppointmentRoute: AppointmentRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  CustomDesignRoute: CustomDesignRoute,
  GalleryRoute: GalleryRoute,
  ShopRoute: ShopRouteWithChildren,
  StudentWorkRoute: StudentWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
